### ISSUE TITLE
[bug] Sometimes, copied objects will not move left (-x)

### ISSUE THREAD

**Issue by Ascyst** [olavim/RoundsMapsExtended#11]
Haven't had this happen to move objects to the right, but sometimes moving copied objects to the left does not work until they're rotated. Might be related to the angle that they're at, as this object was rotated using shift, then copied. 

https://user-images.githubusercontent.com/85650794/154598369-594e1349-0984-4418-bac9-f2e2d37d27f2.mp4

Not shown in video, but I tried scaling the object up and down. No matter how small/large it is, I could not move it to the left until I rotated it. 

Something about grid snapping, as holding shift allows me to move the object fine.

**Comment by Ascyst** [comment]
Quick note, I can move it left if I grab the object and snap the mouse to the left. Then the object starts behaving normally and I can move it freely

Edit: I lied, see clip. 

https://user-images.githubusercontent.com/85650794/154598897-2a81031f-27ca-4b8b-9800-4049aa44a47f.mp4

Seems to be related to position on screen, or maybe position relative to "parent" object?

**Comment by olavim** [comment]
Fixed in v1.0.0
