### ISSUE TITLE
Unable to input non-numeric characters into input boxes for editor

### ISSUE THREAD

**Issue by willuwontu** [olavim/RoundsMapsExtended#16]
Lets say I'm trying to move a box to a position I've determined in an earlier keyframe for an animation for say, `y = -5.5`, if I attempt to directly set the value to `-5.5`, if I type the value into the box, I end up with `y = 55`.

Ideally, I should be able to input `-` and `.` when putting in values for inputs.

**Comment by olavim** [comment]
Fixed in v1.0.4
