### ISSUE TITLE
[Bug] Testing of map not possible

### ISSUE THREAD

**Issue by Bison700** [olavim/RoundsMapsExtended#18]
I cannot test maps. The first time I click »play« it works and I can play the map in the editor like intended.
The second time I try to test the map, the character spawns in the middle of the top outside barrier of the map, resulting in instant death with the splatter animation just visible.

This happens even on a completely new mod profile in r2modman and with everything else erased, only dependencies installed.

Edit:
Actually on another system the bug behaves exactly the same (although other mods have not been uninstalled there).

**Comment by olavim** [comment]
Thanks for reporting. Fixed in v1.2.7
