### ISSUE TITLE
Camera jumps when middle mouse to drag is clicked.

### ISSUE THREAD

**Issue by willuwontu** [olavim/RoundsMapsExtended#4]
https://user-images.githubusercontent.com/11213059/147831859-e8e22e12-9b37-486e-997e-9e4d33a34b61.mp4

Makes it rather difficult to pan around the map.

**Comment by willuwontu** [comment]
Note that it doesn't always jump to the bottom left of the map, it just happened to do so in this case.

**Comment by olavim** [comment]
Gah, released the wrong version. Fixed in v0.9.5.
