### ISSUE TITLE
[bug] Spawn points are scaled by current zoom 

### ISSUE THREAD

**Issue by Ascyst** [olavim/RoundsMapsExtended#6]
https://user-images.githubusercontent.com/85650794/154596150-d78cb3b8-6d18-48e7-92fc-56fc6f1ad4a1.mp4

Intended outcome: Spawn points will have the same scale regardless of zoom level. 
Actual outcome: Spawn points are scaled by zoom level. The more zoomed in you are, the larger their scale will be. 

Reproduction: Create a spawn point while zoomed in, either via spawning one or copy/pasting.

**Comment by olavim** [comment]
Fixed in v1.1.0
