### ISSUE TITLE
[enhancement] Add ability to scale/rotate grouped objects

### ISSUE THREAD

**Issue by Ascyst** [olavim/RoundsMapsExtended#7]
Having the option to scale or rotate a selection of objects would be very handy. 

![image](https://user-images.githubusercontent.com/85650794/154596555-2a932fc7-cacb-4162-92d5-a194db131dd4.png)

As discussed via DM, I personally think that selections including objects that can't be rotated/scaled should have the conflicting objects match the grouped objects change in position.

**Comment by olavim** [comment]
Grouped rotations were added in v1.0.0.

Grouped scaling is not possible, as scaling in Unity does not work like in image editors etc. For example, if you have two map objects A and B, where B is rotated 45 degrees, scaling them both would scale them _in their own axis_.
